// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMpWPe9So4W6Y0ys-LJNxZd9Hre5tX8_I',
    appId: '1:1073287680615:web:2d88e2a8cd0e9f730b3ac2',
    messagingSenderId: '1073287680615',
    projectId: 'disaster-management-55930',
    authDomain: 'disaster-management-55930.firebaseapp.com',
    storageBucket: 'disaster-management-55930.firebasestorage.app',
    measurementId: 'G-B3PBYNBPQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCR3jigcST0srNNGgv2vJKaB8cFhB5DGI',
    appId: '1:1073287680615:android:fb8cb019a9f982980b3ac2',
    messagingSenderId: '1073287680615',
    projectId: 'disaster-management-55930',
    storageBucket: 'disaster-management-55930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVx8H9GnF1Lt6fUb0jgMB0ecTgf3QlO_A',
    appId: '1:1073287680615:ios:7a954448d3f222c60b3ac2',
    messagingSenderId: '1073287680615',
    projectId: 'disaster-management-55930',
    storageBucket: 'disaster-management-55930.firebasestorage.app',
    iosBundleId: 'com.example.projectInt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVx8H9GnF1Lt6fUb0jgMB0ecTgf3QlO_A',
    appId: '1:1073287680615:ios:7a954448d3f222c60b3ac2',
    messagingSenderId: '1073287680615',
    projectId: 'disaster-management-55930',
    storageBucket: 'disaster-management-55930.firebasestorage.app',
    iosBundleId: 'com.example.projectInt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMpWPe9So4W6Y0ys-LJNxZd9Hre5tX8_I',
    appId: '1:1073287680615:web:65ed807a7765d3780b3ac2',
    messagingSenderId: '1073287680615',
    projectId: 'disaster-management-55930',
    authDomain: 'disaster-management-55930.firebaseapp.com',
    storageBucket: 'disaster-management-55930.firebasestorage.app',
    measurementId: 'G-VQ7TWEWHM0',
  );

}